version: '3.3'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
     PGADMIN_DEFAULT_EMAIL: admin@example.com
     PGADMIN_DEFAULT_PASSWORD: password
     PGADMIN_LISTEN_PORT: 80
    ports:
     - "8080:80"
    volumes:
     - pgadmin-data:/var/lib/pgadmin
    links:
     - "db:pgsql-server"

volumes:
  postgres_data:
  pgadmin-data:
